trees/urls.py
from django.contrib import admin
from django.urls import path, include


from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    path('', views.Home.as_view(), name="home"),
    path('planted-tree/<uuid:pk>/', views.DetailTree.as_view(), name='planted-detail'),
    path('planted-tree/account/<uuid:pk>/', views.ListAccountTree.as_view(), name='planted-list'),
    path('planted-tree/add/', views.PlantTreeView.as_view(), name='planted-add'),
    path('planted-tree/api/list', views.JsonView.as_view(), name='json-tree'),
]

admin.site.site_header = "Trees Everywhere Admin"
admin.site.site_title = "Trees Everywhere Admin Portal"
admin.site.index_title = "Welcome to Trees Everywhere"

core/models.py
from django.db import models
from django.contrib.auth.models import User

from core.common.base import BaseModel


class User(User):

    class Meta:
        proxy = True

    def plant_tree(self, tree, loc, age, account=None):
        '''Create new planted tree and return object'''

        tree, created = Tree.objects.get_or_create(
            name=tree,
            defaults={'scientific_name': tree},
        )

        return PlantedTree.objects.create(
            age=age,
            user=self,
            tree=tree,
            lat=loc[0],
            long=loc[1],
            account=account
        )

    def plant_trees(self, plants: list, account=None):
        '''Create list new planted tree and return objects createds'''

        create_list = []

        for obj in plants:

            tree_name = obj[0]
            loc = obj[1]

            obj_tree, created = Tree.objects.get_or_create(
                name=tree_name,
                defaults={'scientific_name': tree_name},
            )
            create_list.append(PlantedTree(
                user=self,
                tree=obj_tree,
                lat=loc[0],
                long=loc[1],
                account=account
            ))

        planted_trees = PlantedTree.objects.bulk_create(create_list)

        return planted_trees

    def get_planted_trees(self):
        '''Return all planteds trees user'''
        return PlantedTree.objects.filter(user=self)

    def get_accounts(self):
        '''Return all accounts user'''
        return Account.objects.filter(users=self)

    @property
    def planteds_count(self):
        '''Return total planteds tree user'''
        return self.get_planted_trees().count()


class Account(BaseModel):
    name = models.CharField('Name', max_length=100)
    users = models.ManyToManyField(User, blank=True, related_name='accounts')
    active = models.BooleanField('Active', default=True)

    def __str__(self):
        return self.name


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(max_length=500, blank=False)

    def __str__(self):
        return self.user.first_name


class Tree(BaseModel):
    name = models.CharField('Name', max_length=100)
    scientific_name = models.CharField('Scientific Name', max_length=150)

    def __str__(self):
        return self.name


class PlantedTree(BaseModel):
    age = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="plantedtree_set")
    tree = models.ForeignKey(Tree, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    lat = models.DecimalField(max_digits=10, decimal_places=8, blank=False, null=False)
    long = models.DecimalField(max_digits=11, decimal_places=8, blank=False, null=False)

    def __str__(self):
        return self.tree.name

core/forms.py
from django import forms
from core.models import PlantedTree


class PlantedCreateForm(forms.ModelForm):
    class Meta:
        model = PlantedTree
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PlantedCreateForm, self).__init__(*args, **kwargs)

core/views.py
import json

from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from django.contrib.auth.mixins import LoginRequiredMixin
from core.common.mixins import IsPlantedMixin
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.core.serializers import serialize


from core.models import PlantedTree
from core.forms import PlantedCreateForm


class Home(LoginRequiredMixin, TemplateView):
    """
        view initial page
    """
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Home, self).get_context_data(*args, **kwargs)
        context = {
            'planteds': self.request.user.get_planted_trees()
        }
        return context


class DetailTree(IsPlantedMixin, DetailView):
    """
        view to detail planted tree
    """

    template_name = 'tree/detail.html'
    model = PlantedTree


class ListAccountTree(LoginRequiredMixin, ListView):
    """
        view to list account planted tree
    """

    template_name = 'tree/list.html'
    model = PlantedTree

    def get_queryset(self):
        account_pk = self.kwargs.get("pk")
        queryset = PlantedTree.objects.filter(account=account_pk)
        return queryset


class PlantTreeView(LoginRequiredMixin, CreateView):
    """
        view to create/post new planted tree
    """
    template_name = 'tree/create.html'
    form_class = PlantedCreateForm
    success_url = "/"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form(self):
        form = super(PlantTreeView, self).get_form()
        form.fields['account'].queryset = self.request.user.get_accounts()
        return form

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PlantTreeView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs


class JsonView(LoginRequiredMixin, TemplateView):
    """
        list all planted trees from logged user
    """
    def get(self, request):

        data = json.loads(serialize('json', request.user.get_planted_trees()))
        return JsonResponse(data, safe=False, content_type="application/json")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Site teste">
    <meta name="author" content="Wellington Castro">

    <title>Trees Everywhere</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>


<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% block sidebar %}
        <!-- Sidebar -->
        <ul class="navbar-nav bg-success sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-tree"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Trees Everywhere<sup>test</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Home</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Account
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                    aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>My Trees</span>
                </a>
                <div id="collapsePages" class="collapse show" aria-labelledby="headingPages"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">options:</h6>
                        <a class="collapse-item" href="{% url 'home' %}">Trees</a>
                        <a class="collapse-item" href="{% url 'planted-add' %}">New Tree</a>
                    </div>
                </div>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                    aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Account Trees</span>
                </a>
                <div id="collapsePages" class="collapse show" aria-labelledby="headingPages"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">accounts:</h6>
                        {% if user.get_accounts %}
                            {% for account in user.get_accounts%}
                            <a class="collapse-item" href="{% url 'planted-list' account.uuid %}">{{ account.name }}</a>
                            {% endfor %}
                        {% else %}
                        <a class="collapse-item" href="#">Accounts not found =(</a>
                        {% endif %}
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        {% endblock %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                {% block topbar %}
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.first_name }}</span>
                                <img class="img-profile rounded-circle" src="{% static 'img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                {% endblock %}


                <!-- Begin Page Content -->
                
                <div class="container-fluid">
                    <!-- Page Heading -->
                    {% block content %}

                    {% endblock %}
                </div>
               
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            {% block footer %}
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Trees Everywhere {% now "Y" %}</span>
                    </div>
                </div>
            </footer>
            {% endblock %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>


    {% block scripts %}
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js '%}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    {% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}

<h1 class="h3 mb-4 text-gray-800">Home</h1>

<div class="row">
    <div class="col-xl-3 col-md-6 mb-4">
        {% include 'widgets/card-info.html' with total=user.planteds_count text='Trees planted(me)' %}
    </div>
</div>

<div class="row">

    <div class="col-lg-8">

        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-success">My trees</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="card-body">
                    {% include 'widgets/card-trees.html' with tree_list=planteds %}
                </div>
            </div>
        </div>

    </div>

    <div class="col-lg-4">

        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardPlant" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-success">Tree</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardPlant">
                <div class="card-body">
                    <strong><a href="{% url 'planted-add' %}">Plant new tree!</a></strong>
                    Thanks
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

templates/tree/create.html
{% extends 'base.html' %}

{% block content %}

<h1 class="h3 mb-4 text-gray-800">Plant Tree</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-success">Create</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="card-body">
                    <form method="post" class="user">
                        {% csrf_token %}
                    
                        {{ form.non_field_errors }}
                    
                        {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                        {% endfor %}
                    
                        <table class="table">
                        {% for field in form.visible_fields %}
                            <tr>
                            <th>{{ field.label_tag }}</th>
                            <td>
                                {{ field.errors }}
                                {{ field }}
                                {{ field.help_text }}
                            </td>
                            </tr>
                        {% endfor %}
                        </table>
                        <br>
                        <button class="btn btn-success btn-user btn-block" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tree/detail.html
{% extends 'base.html' %}


{% block content %}

<h1 class="h3 mb-4 text-gray-800">Planted {{ object.tree }}</h1>

<div class="row">

    <div class="col-lg-12">

        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-success">My trees</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="card-body">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Age</th>
                            <th scope="col">Account</th>
                            <th scope="col">Lat/Long</th>
                            <th scope="col">Planted at</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th>{{ object.tree.name }}</th>
                            <td>{{ object.age }}</td>
                            <td>{{ object.account }}</td>
                            <td>{{ object.lat }}{{ object.long }}</td>
                            <td>{{ object.created_at }}</td>
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

templates/tree/list.html
{% extends 'base.html' %}


{% block content %}

<h1 class="h3 mb-4 text-gray-800">Account Trees</h1>


<div class="row">

    <div class="col-lg-12">

        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                <h6 class="m-0 font-weight-bold text-success">My account trees</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="card-body">
                    {% include 'widgets/card-trees.html' with tree_list=object_list %}
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

templates/widgets/card-info.html
<div class="card border-left-dark shadow h-100 py-2">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                    {{ text }}</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total }}</div>
            </div>
            <div class="col-auto">
                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
            </div>
        </div>
    </div>
</div>

templates/widgets/card-trees.html
<table id="list_trees" class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Account</th>
        <th scope="col">Lat/Long</th>
      </tr>
    </thead>
    <tbody>
    {% for tree in tree_list %}
      <tr>
        <th><a href="{% url 'planted-detail' tree.uuid %}">{{ tree.tree.name }}</a></th>
        <td>{{ tree.age }}</td>
        <td>{{ tree.account }}</td>
        <td>{{ tree.lat }}{{ tree.long }}</td>
      </tr>
    {% endfor %}
    </tbody>
</table>